# Generated by Django 4.2 on 2023-04-27 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='receive_date',
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_date', models.DateField(auto_now_add=True)),
                ('expiration_date', models.DateField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.item')),
            ],
        ),
    ]
