# Generated by Django 4.2 on 2023-04-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_remove_item_expiration_date_remove_item_receive_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='current_price',
            field=models.FloatField(default=0.0),
        ),
    ]
