# Generated by Django 4.2 on 2023-05-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_amortization',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
