# Generated by Django 4.2 on 2023-05-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_item_is_amortization_item_item_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='group',
            field=models.CharField(default='1', max_length=24),
        ),
    ]
