# Generated by Django 4.2 on 2023-05-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_storage_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='group',
            field=models.CharField(default='1', max_length=44),
        ),
    ]
